title: "Sir. Gabriele I Langellotto"
author: "Sir. G.I. Langellotto"
description: "AI Solution Architect | HP Lecturer | Automation Innovation & Business Strategy Expert 🚀 TRANSFORMING COMPLEX TECH CHALLENGES INTO BUSINESS WINS!"

# Email / Social media user names used by the minima theme:
email: "gilangellotto@gmail.com"
github_username: "GIL794"
linkedin_username: "Gabriele Iacopo Langellotto"

# Theme
theme: "minima"

# Plugins - only include what's necessary
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Kramdown configuration
kramdown:
  syntax_highlighter_opts:
    disable: true
    
# Other settings
titles_from_headings:
  strip_title: true
  collections: true

# Default settings for posts
defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
